# Generated by Django 5.1.1 on 2024-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goals',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='goals',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_pdrfdn', upload_to='images/'),
        ),
    ]
