# Generated by Django 5.1.1 on 2024-09-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goals_options_alter_goals_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='image',
            field=models.ImageField(blank=True, default='media/images/default_post_pdrfdn.jpg', upload_to='images/'),
        ),
    ]
