# Generated by Django 5.1.1 on 2024-09-30 21:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goals_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='media/images/default_post_pdrfdn', max_length=255, null=True, verbose_name='image'),
        ),
    ]
