# Generated by Django 5.0.7 on 2024-09-04 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('deadline', models.BooleanField(default=True)),
                ('task_title', models.CharField(max_length=50)),
                ('task_details', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.CharField(blank=True, max_length=150, null=True)),
                ('criteria', models.CharField(blank=True, max_length=150, null=True)),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_for_goals', to='goals.goals')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_tasks', to='tasks.tasks')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
